# This is an example config file for a GPT model.
model = {
    "model_name": "text-davinci-003",
    "temperature": 0.7,
    "max_tokens": 256,
    "top_p": 1.0,
    "frequency_penalty": 0.0,
    "presence_penalty": 0.0,
    "n": 1,
    "best_of": 1,
    "request_timeout": None,
    "_type": "openai",
}
analysis_model = {
    "model_name": "text-davinci-003",
    "temperature": 0.7,
    "max_tokens": 256,
    "top_p": 1.0,
    "frequency_penalty": 0.0,
    "presence_penalty": 0.0,
    "n": 1,
    "best_of": 1,
    "request_timeout": None,
    "_type": "openai",
}
prompter_model = {
    "model_name": "text-davinci-003",
    "temperature": 0.7,
    "max_tokens": 256,
    "top_p": 1.0,
    "frequency_penalty": 0.0,
    "presence_penalty": 0.0,
    "n": 1,
    "best_of": 1,
    "request_timeout": None,
    "_type": "openai",
}
memory_type = "Buffer"  # "Buffer" "BufferWindow" "Summary"
window_size = 3
initialization_message = """
Please provide the email address you signed up for the event with.
"""
template = """You are an AI named Chip working at the Champalimaud Centre for the Unknown who is helping neuroscientists run an experiment on how artificial intelligence can be used to help people to better understand themselves. You are interviewing clients for an art installation called "Latent space 1", which includes a film and a virtual reality experience. Your job is create a virtual reality experience that is customized to each client. Your goal is to surprise the client and make them feel they have learned something about themselves that they didn't know. To do this you first will chat with the client and try to understand them. Next you will create a completely customized movie for the client, entirely generated by machine learning models.

The client's name is {form_item_0}. Begin by introducing yourself and telling a little bit about the context. Do not tell the client about what exactly you are doing unless the client asks. Always ask a question if the client doesn't ask one. Try to find out as much as possible about the client. Ask about issues that a psychologist would be interested in. You are compassionate. Always be friendly, humorous and make the client feel you are like them.

Current conversation:
{history}
Client: {input}
AI:"""  # note these must be history and input!
human_prefix = "Client"
ai_prefix = "AI"
first_message = """Who are you?"""
analysis_template = """Below is a conversation between Client and AI. Based on the conversation with the Client, tell this story in 6 scenes, with each scene having a setting in the form of a landscape or other scene. Do not include information about the installation itself.

Conversation:
{history}"""
# Prompter Model
concept_examples = [
    {
        "statement": "Client dreamt of a woman who was crying.",
        "concept": """
a woman crying in the rain with a sad look on her face
""",
    },
    {
        "statement": "Client and woman had a relationship in the past.",
        "concept": """
two people, who were in love with each other, long ago
""",
    },
    {
        "statement": "Therapist asked questions to gain further details of the dream.",
        "concept": """
a psychologist sitting in an office, analyzing a person's dreams
""",
    },
    {
        "statement": "Client enjoys playing piano for an audience.",
        "concept": """
a beautiful grand piano in a concert hall
""",
    },
]
